version: "3.8"
services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: service
    ports:
      - "5432:5432"
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  postgres_data: